apiVersion: v1
kind: Service
metadata:
  name: todoapp-be-svc
  labels:
    app: todoapp
    tier: backend
spec:
  selector:
    app: todoapp
    tier: backend
  ports:
  - port: {{ .Values.backend_port }}