apiVersion: v1
kind: Service
metadata:
  name: todoapp-db-svc
  labels:
    app: todoapp
    tier: database
spec:
  selector:
    app: todoapp
    tier: database
  ports:
  - port: {{ .Values.mariadb_port }}