apiVersion: v1
kind: Service
metadata:
  name: todoapp-fe-svc
  labels:
    app: todoapp
    tier: frontend
spec:
  selector:
    app: todoapp
    tier: frontend
  ports:
  - port: {{ .Values.frontend_port }}