apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: todoapp-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
  labels:
    name: todoapp-ingress
spec:
  rules:
  - host: todoapp.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: todoapp-fe-svc
            port: 
              number: {{ .Values.frontend_port }}
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: todoapp-be-svc
            port:
              number: {{ .Values.backend_port }}
